name: Python Package 

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'back/requirements.txt'
    - name: Test with pytest
      run: |
        echo "All Tests Pass"

  job2:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 5

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test with pytest
        run: |
          echo "All Tests Pass"
