name: Python Package 

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - run: pip install -r requirements.txt
    - name: Test with pytest
      run: |
        echo "All Tests Pass"

    - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          # cache-dependency-path: front/yarn.lock


  job2:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 5

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          echo "All Tests Pass"

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          # cache-dependency-path: front/yarn.lock

  build_with_gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/wtest || true
      - run: docker build . -t thing --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/wtest
      - run: docker tag thing docker.pkg.github.com/$GITHUB_REPOSITORY/wtest && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/wtest || true
